version: '3.5'

services:
  react-docker:
    build: .
    container_name: mern-test
    restart: always
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
#    volumes:
#      - '.:/usr/src/app'
#      - '/usr/src/app/node_modules'
    environment:
          - NODE_ENV=development
          - CHOKIDAR_USEPOLLING=true
#    links:
#      - mongo
#  mongo:
#    container_name: mongo
#    image: mongo
#    volumes:
#      - ./data:/data/db
#    ports:
#      - "27017:27017"
#    command: mongod --noauth --smallfiles